---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "default"
---


```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
library(readr)
sklep_rowerowy <- read_csv("sklep_rowerowy.csv")
```


#Pakiet NANIAR do analizowania braków danych
```{r}
install.packages("naniar")
library(naniar)
```

# Zliczanie całkowitej liczby NA
```{r}
n_miss(sklep_rowerowy)
```
# Zliczanie całkowitej liczby kompletnych wartości
```{r}
n_complete(sklep_rowerowy)
``` 

# Procent braków
```{r}
prop_miss(sklep_rowerowy)
```
# Tabela podsumowująca NA
```{r}
miss_var_summary(sklep_rowerowy)
```

# Wizualizacja NA
```{r}
vis_miss(sklep_rowerowy)
```


#Wizualizacja ogólnej liczby NA

```{r}
cluster = TRUE
sort_miss = TRUE 
gg_miss_fct(sklep_rowerowy, Gender)
```
# Przekroje NA
```{r}
gg_miss_upset(sklep_rowerowy,
              nsets=53)
```

# Instalujemy pakiety
```{r include=FALSE}
if(!require("tidyverse")) install.packages("tidyverse")
if(!require("dlookr")) install.packages("dlookr")
if(!require("editrules")) install.packages("editrules") #reguły 
if(!require("VIM")) install.packages("VIM")
if(!require("validate")) install.packages("validate")

library(tidyverse)
library(dlookr)
library(editrules) #reguły
library(VIM)
library(validate)
```

#Reguły:
```{r}
reguly <- editset(c( 
  "Age>=30",
  "Age<=50",
  "Income>=30000" ))
```

#Walidacja:
```{r}
summary(violatedEdits(reguly,sklep_rowerowy))
bledy <- violatedEdits(reguly,sklep_rowerowy)
plot(bledy)

sklep_rowerowy %>% 
  filter(Age > 50)
```

#Poprawiam błędy w danych
```{r}
sklep_rowerowy[localizeErrors(reguly,sklep_rowerowy)$adapt] <- NA
```

